import type { ConstructionEstimateResponse } from "./cost-types";

function currency(value: number) {
  return `₹${Math.round(value).toLocaleString("en-IN")}`;
}

export function buildConstructionReportHtml(
  estimate: ConstructionEstimateResponse,
) {
  const dpr = estimate.dprReport;

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Construction DPR</title>

<style>
body{
  font-family: Arial, sans-serif;
  padding:40px;
  color:#111827;
}

h1{
  font-size:28px;
  margin-bottom:4px;
}

h2{
  margin-top:36px;
  border-bottom:1px solid #d1d5db;
  padding-bottom:8px;
}

table{
  width:100%;
  border-collapse:collapse;
  margin-top:16px;
}

th,td{
  border:1px solid #d1d5db;
  padding:10px;
  font-size:13px;
}

th{
  background:#f3f4f6;
  text-align:left;
}

.summary-grid{
  display:grid;
  grid-template-columns:1fr 1fr;
  gap:12px;
  margin-top:20px;
}

.card{
  border:1px solid #d1d5db;
  padding:14px;
  border-radius:8px;
}

.note{
  margin-top:10px;
  font-size:12px;
  color:#4b5563;
}
</style>
</head>

<body>

<h1>3Bigha Construction DPR</h1>

<div>
Generated:
${new Date().toLocaleString("en-IN")}
</div>

<h2>Project Summary</h2>

<div class="summary-grid">
  <div class="card">
    <strong>Project Cost</strong><br/>
    ${currency(estimate.summary.estimatedBudget)}
  </div>

  <div class="card">
    <strong>Rate per Sq.ft</strong><br/>
    ${currency(estimate.summary.estimatedRatePerSqFt)}
  </div>

  <div class="card">
    <strong>Project Area</strong><br/>
    ${estimate.request.builtUpAreaSqFt.toLocaleString("en-IN")} sq.ft
  </div>

  <div class="card">
    <strong>Floors</strong><br/>
    ${(estimate.request.floorCount ?? 1).toLocaleString("en-IN")}
  </div>
</div>

<h2>Costing Breakdown</h2>

<table>
<tr>
<th>Category</th>
<th>Amount</th>
</tr>

<tr>
<td>Civil Works</td>
<td>${currency(estimate.costing.civilCost)}</td>
</tr>

<tr>
<td>Finishing</td>
<td>${currency(estimate.costing.finishingCost)}</td>
</tr>

<tr>
<td>Electrical</td>
<td>${currency(estimate.costing.electricalCost)}</td>
</tr>

<tr>
<td>Plumbing</td>
<td>${currency(estimate.costing.plumbingCost)}</td>
</tr>

<tr>
<td>Interior</td>
<td>${currency(estimate.costing.interiorCost)}</td>
</tr>
</table>

${
  estimate.roomPlanning
    ? `
<h2>Architectural Planning</h2>

<table>
<tr><th>Planning Item</th><th>Value</th></tr>

<tr>
<td>Bedrooms</td>
<td>${estimate.roomPlanning.estimatedBedrooms}</td>
</tr>

<tr>
<td>Bathrooms</td>
<td>${estimate.roomPlanning.estimatedBathrooms}</td>
</tr>

<tr>
<td>Parking Slots</td>
<td>${estimate.roomPlanning.estimatedParkingSlots}</td>
</tr>

<tr>
<td>Efficiency Ratio</td>
<td>${estimate.roomPlanning.efficiencyPercent}%</td>
</tr>
</table>
`
    : ""
}

${
  estimate.pwdItemization
    ? `
<h2>PWD Itemization</h2>

<table>
<tr>
<th>Code</th>
<th>Description</th>
<th>Qty</th>
<th>Unit</th>
<th>Rate</th>
<th>Amount</th>
</tr>

${[
  ...estimate.pwdItemization.civilItems,
  ...estimate.pwdItemization.plumbingItems,
  ...estimate.pwdItemization.electricalItems,
  ...estimate.pwdItemization.finishingItems,
]
  .map(
    (item) => `
<tr>
<td>${item.itemCode}</td>
<td>${item.description}</td>
<td>${item.quantity}</td>
<td>${item.unit}</td>
<td>${currency(item.rate)}</td>
<td>${currency(item.amount)}</td>
</tr>
`,
  )
  .join("")}
</table>
`
    : ""
}

${
  dpr
    ? `
<h2>Recommendations</h2>

<ul>
${dpr.recommendations
  .map((item) => `<li>${item}</li>`)
  .join("")}
</ul>
`
    : ""
}

<div class="note">
Generated by 3Bigha AI Construction Operating System
</div>

</body>
</html>
`;
}
