import type { ProcurementTriggerRule } from "./procurement-phase-types";

export const PROCUREMENT_TRIGGER_RULES: ProcurementTriggerRule[] = [
  {
    phaseKey: "planning",
    triggerType: "service",
    title: "Finalize drawings and site supervision",
    description:
      "Confirm engineer, site supervisor, layout marking and project execution plan.",
    recommendedLeadDays: 7,
    priority: "high",
    vendorCategory: "Engineer / Site Supervisor",
    rfqCategory: "services",
    rfqReadyName: "Engineer and site supervision service",
    note: "Planning delay affects every later construction phase.",
  },
  {
    phaseKey: "foundation",
    triggerType: "service",
    title: "Book excavation contractor",
    description:
      "Arrange excavation team or machine before foundation layout starts.",
    recommendedLeadDays: 5,
    priority: "high",
    vendorCategory: "Earthwork Contractor",
    rfqCategory: "services",
    rfqReadyName: "Foundation excavation contractor",
    note: "Soil condition and machine availability can delay foundation work.",
  },
  {
    phaseKey: "foundation",
    triggerType: "material",
    title: "Procure cement, sand, aggregate and TMT for foundation",
    description:
      "Arrange core construction materials before foundation concreting begins.",
    recommendedLeadDays: 6,
    priority: "critical",
    vendorCategory: "Building Material Supplier",
    rfqCategory: "materials",
    rfqReadyName: "Foundation cement sand aggregate TMT supply",
    note: "Foundation cannot proceed without timely material delivery.",
  },
  {
    phaseKey: "rcc",
    triggerType: "material",
    title: "Procure RCC cement, TMT, chips and shuttering support",
    description:
      "Prepare RCC material supply and shuttering support before slab/beam/column work.",
    recommendedLeadDays: 8,
    priority: "critical",
    vendorCategory: "RCC Material Supplier",
    rfqCategory: "materials",
    rfqReadyName: "RCC cement TMT aggregate supply",
    note: "RCC work is highly schedule-sensitive due to shuttering and curing cycles.",
  },
  {
    phaseKey: "rcc",
    triggerType: "rental",
    title: "Arrange shuttering and concrete equipment",
    description:
      "Book shuttering material, mixer, vibrator or lifting support if required.",
    recommendedLeadDays: 7,
    priority: "high",
    vendorCategory: "Construction Equipment Rental",
    rfqCategory: "rentals",
    rfqReadyName: "Shuttering and concrete equipment rental",
    note: "Rental availability should be confirmed before RCC work starts.",
  },
  {
    phaseKey: "brickwork",
    triggerType: "material",
    title: "Procure bricks or blocks",
    description:
      "Arrange brick/block supply before masonry team starts wall work.",
    recommendedLeadDays: 5,
    priority: "high",
    vendorCategory: "Brick / Block Supplier",
    rfqCategory: "materials",
    rfqReadyName: "Brick or block supply",
    note: "Brick quality, delivery and unloading should be confirmed in advance.",
  },
  {
    phaseKey: "brickwork",
    triggerType: "labour",
    title: "Confirm masonry labour",
    description:
      "Book mason team for wall masonry and partition work.",
    recommendedLeadDays: 4,
    priority: "medium",
    vendorCategory: "Masonry Contractor",
    rfqCategory: "services",
    rfqReadyName: "Masonry labour contractor",
    note: "Mason availability controls wall completion speed.",
  },
  {
    phaseKey: "electrical_plumbing_rough",
    triggerType: "service",
    title: "Finalize electrical and plumbing rough-in contractors",
    description:
      "Confirm concealed wiring, pipe routing, bathroom and kitchen line contractors.",
    recommendedLeadDays: 6,
    priority: "high",
    vendorCategory: "Electrical / Plumbing Contractor",
    rfqCategory: "services",
    rfqReadyName: "Electrical and plumbing rough-in work",
    note: "Rough-in must be completed before plastering.",
  },
  {
    phaseKey: "plaster",
    triggerType: "material",
    title: "Procure plaster materials",
    description:
      "Arrange cement, sand and related plaster materials before plaster team starts.",
    recommendedLeadDays: 4,
    priority: "medium",
    vendorCategory: "Building Material Supplier",
    rfqCategory: "materials",
    rfqReadyName: "Plaster cement and sand supply",
    note: "Material moisture and sand quality affect plaster finish.",
  },
  {
    phaseKey: "flooring",
    triggerType: "material",
    title: "Procure tiles and flooring materials",
    description:
      "Finalize tile design, quantity, adhesive and grout before flooring starts.",
    recommendedLeadDays: 10,
    priority: "high",
    vendorCategory: "Tile Supplier",
    rfqCategory: "materials",
    rfqReadyName: "Floor tiles and flooring material supply",
    note: "Tile design selection can delay finishing if not finalized early.",
  },
  {
    phaseKey: "doors_windows",
    triggerType: "material",
    title: "Order doors, windows and grills",
    description:
      "Finalize measurements, material type and fabrication vendor before installation phase.",
    recommendedLeadDays: 14,
    priority: "high",
    vendorCategory: "Door / Window Vendor",
    rfqCategory: "materials",
    rfqReadyName: "Door window grill supply and fitting",
    note: "Fabrication items need longer lead time.",
  },
  {
    phaseKey: "painting",
    triggerType: "material",
    title: "Procure paint, putty and primer",
    description:
      "Select paint brand, finish and quantity before surface preparation starts.",
    recommendedLeadDays: 5,
    priority: "medium",
    vendorCategory: "Paint Supplier",
    rfqCategory: "materials",
    rfqReadyName: "Paint putty primer supply",
    note: "Paint work depends on surface dryness and final shade selection.",
  },
  {
    phaseKey: "final_finishing",
    triggerType: "material",
    title: "Procure sanitary, electrical fittings and hardware",
    description:
      "Arrange final bathroom fittings, switches, lights, locks, handles and accessories.",
    recommendedLeadDays: 12,
    priority: "high",
    vendorCategory: "Finishing Material Supplier",
    rfqCategory: "materials",
    rfqReadyName: "Final finishing fittings and hardware supply",
    note: "Finishing items often delay handover if selected late.",
  },
  {
    phaseKey: "handover",
    triggerType: "inspection",
    title: "Prepare final inspection and snag list",
    description:
      "Check finishing, leakage, electrical points, paint defects and pending correction items.",
    recommendedLeadDays: 3,
    priority: "medium",
    vendorCategory: "Site Supervisor",
    rfqCategory: "services",
    rfqReadyName: "Final inspection and snag correction",
    note: "Snag correction should be completed before handover.",
  },
];