import {redirect} from"next/navigation";import {requireMasterAdmin} from"@/lib/admin/requireMasterAdmin";
export const dynamic="force-dynamic";
const authorities=[
 {key:"properties",label:"Properties",table:"property_listings",href:"/admin/property"},
 {key:"projects",label:"Builder projects",table:"builder_projects",href:"/admin/property/projects"},
 {key:"materials",label:"Materials",table:"material_listings",href:"/admin/materials"},
 {key:"rentals",label:"Rentals",table:"rental_listings",href:"/admin/rentals"},
 {key:"services",label:"Services",table:"service_listings",href:"/admin/services"},
 {key:"turnkey",label:"Turnkey packages",table:"turnkey_packages",href:"/admin/services"},
] as const;
async function count(admin:any,table:string,status?:string){let q=admin.from(table).select("*",{count:"exact",head:true});if(status)q=q.eq("status",status);const{count,error}=await q;return{count:error?null:count??0,error:error?.message||null}}
export default async function MarketplaceControl(){const access=await requireMasterAdmin();if("error"in access){if(access.status===401)redirect("/login?next=/admin/marketplace-control");return <main>Access denied</main>}const results=await Promise.all(authorities.map(async x=>({x,total:await count(access.admin,x.table),pending:await count(access.admin,x.table,"pending")})));const issues=results.flatMap(r=>[r.total.error,r.pending.error].filter(Boolean));return <main style={{padding:24,background:"#f8fafc",minHeight:"100vh"}}><header><h1>Marketplace Control Center</h1><p>One command surface for marketplace supply, moderation queues, promotions and operating health.</p><a href="/admin/dashboard">← Admin Command Center</a></header>{issues.length?<details style={{marginTop:12}}><summary>Partial data notice ({issues.length})</summary>{issues.map((x,i)=><p key={i}>{x}</p>)}</details>:null}<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12,marginTop:18}}>{results.map(({x,total,pending})=><a key={x.key} href={x.href} style={{padding:16,border:"1px solid #dbe3ec",borderRadius:12,background:"white",color:"inherit",textDecoration:"none"}}><small>{x.label}</small><strong style={{display:"block",fontSize:30}}>{total.count??"—"}</strong><span>{pending.count??"—"} awaiting review</span></a>)}</section><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12,marginTop:18}}><article style={{padding:16,background:"white",border:"1px solid #ddd",borderRadius:12}}><h2>Visibility & promotions</h2><p>Featured placement, boost priority, risk and reputation remain governed by the existing Vendor Control authority.</p><a href="/admin/dashboard/vendor-control">Open Vendor Control</a></article><article style={{padding:16,background:"white",border:"1px solid #ddd",borderRadius:12}}><h2>Market intelligence</h2><p>Demand, supply, shortage, liquidity and expansion signals remain in the existing intelligence engine.</p><a href="/admin/dashboard/marketplace-intelligence">Open Marketplace Intelligence</a></article><article style={{padding:16,background:"white",border:"1px solid #ddd",borderRadius:12}}><h2>AI moderation</h2><p>Review media mismatches and duplicate evidence before publication.</p><a href="/admin/moderation">Open AI Moderation</a></article></section></main>}
