export const MATERIAL_KEYWORDS = [
  // Cement
  "cement",
  "cement supplier",
  "cement dealer",
  "cement dokan",
  "cement shop",
  "cement wholesale",
  "cement price",
  "cement rate today",
  "opc cement",
  "ppc cement",
  "psc cement",
  "white cement",
  "ultratech cement",
  "acc cement",
  "ambuja cement",
  "dalmia cement",
  "emami cement",
  "lafarge cement",
  "star cement",
  "ramco cement",

  // Steel / Rod
  "rod",
  "iron rod",
  "steel rod",
  "tmt bar",
  "tmt rod",
  "saria",
  "sariya",
  "steel supplier",
  "rod dealer",
  "rod price",
  "tmt bar price",
  "8mm rod",
  "10mm rod",
  "12mm rod",
  "16mm rod",
  "20mm rod",
  "25mm rod",
  "binding wire",
  "barbed wire",
  "wire mesh",
  "ms angle",
  "ms channel",
  "ms flat",
  "ms pipe",
  "gi pipe",
  "square pipe",

  // Sand / Balu
  "sand",
  "balu",
  "baalu",
  "construction sand",
  "river sand",
  "fine sand",
  "coarse sand",
  "medium sand",
  "local balu",
  "lal balu",
  "white sand",
  "washed sand",
  "sand supplier",
  "balu supplier",
  "balu dealer",
  "balu price",
  "sand price",
  "balu rate",
  "sand rate today",
  "balu truck",
  "tractor balu",

  // Stone / Chips / Gitti
  "pathor",
  "stone",
  "stone chips",
  "chips",
  "gitti",
  "giti",
  "aggregate",
  "construction aggregate",
  "10mm chips",
  "20mm chips",
  "40mm chips",
  "stone dust",
  "crusher dust",
  "khoya",
  "metal chips",
  "stone supplier",
  "pathor supplier",
  "gitti supplier",
  "chips supplier",
  "stone chips price",
  "pathor price",
  "gitti price",

  // Bricks / Blocks
  "brick",
  "bricks",
  "it",
  "eet",
  "lal it",
  "red brick",
  "first class brick",
  "fly ash brick",
  "cement brick",
  "concrete block",
  "aac block",
  "hollow block",
  "solid block",
  "paver block",
  "interlocking paver",
  "brick supplier",
  "it supplier",
  "brick dealer",
  "brick price",
  "fly ash brick price",
  "aac block price",

  // Concrete / RCC
  "ready mix concrete",
  "rmc",
  "concrete",
  "rcc material",
  "rcc concrete",
  "mortar",
  "plaster mortar",
  "construction mix",
  "concrete supplier",
  "rmc supplier",
  "ready mix concrete price",

  // Doors
  "door",
  "dorja",
  "darja",
  "kather dorja",
  "wooden door",
  "flush door",
  "plywood door",
  "panel door",
  "steel door",
  "iron door",
  "pvc door",
  "fiber door",
  "glass door",
  "aluminium door",
  "sliding door",
  "bathroom door",
  "main door",
  "door frame",
  "wooden frame",
  "chowkath",
  "door lock",
  "door handle",
  "door hinges",
  "door dealer",
  "door supplier",
  "wooden door price",
  "kather dorja price",

  // Windows
  "window",
  "janla",
  "janala",
  "aluminium janla",
  "aluminium window",
  "sliding window",
  "wooden window",
  "pvc window",
  "upvc window",
  "glass window",
  "window frame",
  "window grill",
  "mosquito net window",
  "window supplier",
  "janla dealer",
  "aluminium window price",
  "sliding janla price",

  // Grill / Gate / Fabrication
  "grill",
  "iron grill",
  "window grill",
  "gate",
  "iron gate",
  "steel gate",
  "main gate",
  "collapsible gate",
  "rolling shutter",
  "shutter",
  "shop shutter",
  "ms gate",
  "ss railing",
  "stair railing",
  "balcony railing",
  "grill supplier",
  "gate supplier",
  "rolling shutter price",

  // Wood / Board / Hardware
  "wood",
  "kath",
  "timber",
  "plywood",
  "ply",
  "sunmica",
  "laminate",
  "veneer",
  "block board",
  "mdf board",
  "particle board",
  "hard board",
  "commercial ply",
  "marine ply",
  "waterproof ply",
  "hardware",
  "hardware dokan",
  "hardware shop",
  "hinges",
  "lock",
  "handle",
  "tower bolt",
  "latch",
  "screw",
  "nail",
  "nut bolt",
  "adhesive",
  "fevicol",
  "silicone sealant",

  // Tiles / Flooring
  "tiles",
  "floor tiles",
  "wall tiles",
  "bathroom tiles",
  "kitchen tiles",
  "vitrified tiles",
  "ceramic tiles",
  "porcelain tiles",
  "parking tiles",
  "outdoor tiles",
  "anti skid tiles",
  "marble",
  "granite",
  "stone slab",
  "flooring material",
  "tile adhesive",
  "tile grout",
  "tiles shop",
  "tiles dealer",
  "tiles price",
  "marble price",
  "granite price",

  // Paint / Wall finishing
  "paint",
  "wall paint",
  "house paint",
  "interior paint",
  "exterior paint",
  "primer",
  "putty",
  "wall putty",
  "distemper",
  "enamel paint",
  "texture paint",
  "waterproof paint",
  "asian paint",
  "berger paint",
  "nerolac paint",
  "dulux paint",
  "paint dealer",
  "paint shop",
  "paint price",
  "putty price",

  // Plumbing
  "plumbing material",
  "pipe",
  "pvc pipe",
  "cpvc pipe",
  "upvc pipe",
  "gi pipe",
  "hdpe pipe",
  "ppr pipe",
  "pipe fitting",
  "elbow",
  "tee",
  "socket",
  "union",
  "valve",
  "ball valve",
  "tap",
  "tep kol",
  "kol",
  "water tap",
  "bib cock",
  "pillar cock",
  "mixer tap",
  "shower",
  "health faucet",
  "water tank",
  "sintex tank",
  "overhead tank",
  "plumbing supplier",
  "pipe dealer",
  "tep kol price",

  // Sanitary / Bathroom
  "sanitary",
  "sanitary ware",
  "bathroom fitting",
  "commode",
  "western commode",
  "indian pan",
  "basin",
  "wash basin",
  "sink",
  "kitchen sink",
  "flush tank",
  "concealed cistern",
  "urinal",
  "bathroom accessories",
  "soap holder",
  "towel rod",
  "bathroom mirror",
  "jaquar fitting",
  "hindware",
  "cera sanitary",
  "parryware",
  "sanitary shop",
  "sanitary dealer",
  "bathroom fitting price",

  // Electrical
  "electrical material",
  "electric material",
  "wire",
  "electric wire",
  "electric tar",
  "cable",
  "house wiring cable",
  "copper wire",
  "aluminium wire",
  "switch",
  "socket",
  "switch board",
  "mcb",
  "mccb",
  "db box",
  "distribution box",
  "fan",
  "ceiling fan",
  "exhaust fan",
  "led light",
  "tube light",
  "panel light",
  "inverter",
  "battery",
  "stabilizer",
  "earthing material",
  "conduit pipe",
  "anchor switch",
  "havells wire",
  "finolex wire",
  "polycab wire",
  "electrical shop",
  "electrical dealer",

  // Roofing
  "roofing sheet",
  "tin",
  "tata tin",
  "color coated sheet",
  "gc sheet",
  "gi sheet",
  "polycarbonate sheet",
  "roof tile",
  "roofing material",
  "rain gutter",
  "ridge cap",
  "roof screw",
  "roofing sheet price",
  "tin price",

  // Ceiling / Partition
  "false ceiling",
  "gypsum board",
  "pop",
  "pvc ceiling",
  "ceiling channel",
  "partition board",
  "cement board",
  "calcium silicate board",
  "ceiling material",
  "false ceiling material",
  "gypsum board price",

  // Glass
  "glass",
  "window glass",
  "door glass",
  "toughened glass",
  "tempered glass",
  "frosted glass",
  "mirror",
  "glass partition",
  "glass railing",
  "glass dealer",
  "glass shop",
  "toughened glass price",

  // Kitchen
  "kitchen appliances",
  "kitchen chimney",
  "chimney",
  "hob",
  "gas oven",
  "gas stove",
  "cooktop",
  "modular kitchen",
  "kitchen basket",
  "kitchen trolley",
  "sink mixer",
  "kitchen sink",
  "exhaust fan",
  "chimney dealer",
  "chimney price",
  "modular kitchen material",

  // Water / Pump
  "submersible pump",
  "water pump",
  "motor pump",
  "borewell pump",
  "pump pipe",
  "pump starter",
  "pump controller",
  "water motor",
  "pump dealer",
  "submersible price",

  // Waterproofing / Chemicals
  "waterproofing",
  "waterproofing chemical",
  "dr fixit",
  "sika chemical",
  "tile adhesive",
  "construction chemical",
  "admixture",
  "primer chemical",
  "wall sealer",
  "roof coating",
  "dampproof chemical",

  // Construction Tools / Consumables
  "construction tools",
  "mistri tools",
  "trowel",
  "hammer",
  "measuring tape",
  "level pipe",
  "spirit level",
  "cutter blade",
  "drill bit",
  "welding rod",
  "safety helmet",
  "safety shoes",
  "gloves",
  "tarpaulin",
  "plastic sheet",
];

export function getMaterialKeywords(area: string) {
  const cleanArea = area.trim();

  return MATERIAL_KEYWORDS.flatMap((word) => [
    `${word} in ${cleanArea}`,
    `${word} near me in ${cleanArea}`,
    `${word} supplier in ${cleanArea}`,
    `${word} dealer in ${cleanArea}`,
    `${word} shop in ${cleanArea}`,
    `${word} dokan in ${cleanArea}`,
    `${word} price in ${cleanArea}`,
    `${word} rate today in ${cleanArea}`,
    `${word} wholesale in ${cleanArea}`,
    `best ${word} in ${cleanArea}`,
    `post requirement for ${word} in ${cleanArea}`,
  ]);
}