import type { SeoModule } from "@/lib/geo/india-geo";

export type RegionalKeywordIntent =
  | "search"
  | "near_me"
  | "price"
  | "supplier"
  | "dealer"
  | "wholesale"
  | "rfq"
  | "service"
  | "repair"
  | "rental"
  | "installation";

export type RegionalKeywordItem = {
  keyword: string;
  intent: RegionalKeywordIntent;
};

const propertyWords = [
  "land",
  "plot",
  "jomi",
  "jamin",
  "bastu jomi",
  "chash jomi",
  "commercial land",
  "residential plot",
  "flat",
  "house",
  "bari",
  "duplex house",
  "apartment",
  "shop",
  "godown",
  "warehouse",
  "office space",
  "commercial property",
  "builder project",
  "new project",
  "ready flat",
  "under construction flat",
  "real estate",
  "property dealer",
  "land broker",
  "plot broker",
  "property agent",
  "land for sale",
  "flat for sale",
  "house for sale",
  "shop for rent",
  "office for rent",
  "godown rent",
  "warehouse rent",
  "investment property",
  "low budget land",
  "cheap land",
  "road side land",
  "highway land",
  "market area land",
  "school near property",
  "hospital near property",
  "corner plot",
  "boundary wall land",
  "mutation land",
  "clear title property",
  "registered land",
];

const materialWords = [
  "cement",
  "opc cement",
  "ppc cement",
  "ultratech cement",
  "acc cement",
  "ambuja cement",
  "dalmia cement",
  "emami cement",
  "cement dealer",
  "cement supplier",
  "rod",
  "iron rod",
  "steel rod",
  "tmt bar",
  "saria",
  "steel",
  "binding wire",
  "wire mesh",
  "balu",
  "sand",
  "river sand",
  "coarse sand",
  "fine sand",
  "lal balu",
  "local balu",
  "pathor",
  "stone chips",
  "gitti",
  "aggregate",
  "10mm chips",
  "20mm chips",
  "40mm chips",
  "brick",
  "it",
  "lal it",
  "fly ash brick",
  "cement brick",
  "block",
  "aac block",
  "hollow block",
  "ready mix concrete",
  "rmc",
  "concrete",
  "mortar",
  "tiles",
  "floor tiles",
  "wall tiles",
  "bathroom tiles",
  "kitchen tiles",
  "vitrified tiles",
  "ceramic tiles",
  "marble",
  "granite",
  "stone slab",
  "paver block",
  "door",
  "dorja",
  "kather dorja",
  "wooden door",
  "flush door",
  "plywood door",
  "steel door",
  "pvc door",
  "fiber door",
  "glass door",
  "aluminium door",
  "window",
  "janla",
  "aluminium janla",
  "sliding janla",
  "wooden window",
  "grill",
  "iron grill",
  "gate",
  "shutter",
  "rolling shutter",
  "collapsible gate",
  "plywood",
  "ply",
  "sunmica",
  "laminate",
  "veneer",
  "block board",
  "mdf board",
  "particle board",
  "hardware",
  "hinges",
  "lock",
  "handle",
  "tower bolt",
  "screw",
  "nail",
  "paint",
  "wall paint",
  "primer",
  "putty",
  "asian paint",
  "berger paint",
  "nerolac paint",
  "waterproofing",
  "tar felt",
  "roof coating",
  "plumbing pipe",
  "pvc pipe",
  "cpvc pipe",
  "upvc pipe",
  "gi pipe",
  "pipe fitting",
  "tap",
  "tep kol",
  "water tap",
  "bathroom fitting",
  "sanitary",
  "commode",
  "basin",
  "sink",
  "shower",
  "flush tank",
  "water tank",
  "sintex tank",
  "submersible pump",
  "motor pump",
  "borewell pipe",
  "electrical wire",
  "electric tar",
  "cable",
  "switch",
  "socket",
  "mcb",
  "db box",
  "fan",
  "light",
  "led light",
  "inverter",
  "battery",
  "roofing sheet",
  "tin",
  "tata tin",
  "color coated sheet",
  "polycarbonate sheet",
  "false ceiling",
  "gypsum board",
  "pop",
  "pvc ceiling",
  "partition board",
  "glass",
  "toughened glass",
  "mirror",
  "kitchen chimney",
  "chimney",
  "hob",
  "gas oven",
  "modular kitchen",
  "kitchen basket",
  "sink mixer",
  "kitchen appliances",
  "exhaust fan",
];

const serviceWords = [
  "contractor",
  "building contractor",
  "civil contractor",
  "house construction contractor",
  "rajmistri",
  "mistri",
  "mason",
  "labour",
  "labour contractor",
  "construction labour",
  "architect",
  "engineer",
  "civil engineer",
  "building planner",
  "house plan",
  "3d elevation",
  "interior designer",
  "turnkey construction",
  "plumber",
  "tep kol mistri",
  "pipe mistri",
  "sanitary mistri",
  "electrician",
  "electric mistri",
  "wiring mistri",
  "painter",
  "paint mistri",
  "tiles mistri",
  "marble mistri",
  "granite fitting",
  "flooring contractor",
  "false ceiling mistri",
  "pop mistri",
  "gypsum ceiling",
  "carpenter",
  "kath mistri",
  "door fitting",
  "window fitting",
  "aluminium mistri",
  "grill mistri",
  "welder",
  "fabricator",
  "gate maker",
  "shutter mistri",
  "waterproofing contractor",
  "roof repair",
  "roof casting",
  "centering mistri",
  "shuttering mistri",
  "rcc work",
  "boundary wall contractor",
  "renovation contractor",
  "repair contractor",
  "home repair",
  "bathroom renovation",
  "kitchen renovation",
  "modular kitchen service",
  "chimney installation",
  "chimney repair",
  "borewell service",
  "submersible repair",
  "pump mechanic",
  "solar installer",
  "cctv installation",
  "lift installation",
  "land surveyor",
  "mutation consultant",
  "legal property consultant",
  "vastu consultant",
];

const rentalWords = [
  "jcb rental",
  "jcb rent",
  "jcb bhara",
  "excavator rental",
  "poclain rental",
  "tractor rental",
  "dumper rental",
  "truck rental",
  "mini truck rental",
  "pickup van rental",
  "concrete mixer rental",
  "mixer machine rent",
  "vibrator machine rent",
  "centering materials rent",
  "shuttering rent",
  "shuttering plate rent",
  "scaffolding rent",
  "bamboo rent",
  "ladder rent",
  "generator rent",
  "welding machine rent",
  "drill machine rent",
  "tiles cutter rent",
  "water pump rent",
  "earth cutting machine",
  "road roller rent",
  "crane rent",
  "house rent",
  "shop rent",
  "office rent",
  "godown rent",
  "warehouse rent",
  "land lease",
  "commercial space rent",
];

function baseWords(module: SeoModule) {
  if (module === "property") return propertyWords;
  if (module === "materials") return materialWords;
  if (module === "services") return serviceWords;
  return rentalWords;
}

export function getRegionalKeywords(
  module: SeoModule,
  area: string
): RegionalKeywordItem[] {
  const cleanArea = area.trim();
  const words = baseWords(module);

  return words.flatMap((word) => {
    const items: RegionalKeywordItem[] = [
      { keyword: `${word} in ${cleanArea}`, intent: "search" },
      { keyword: `${word} near me in ${cleanArea}`, intent: "near_me" },
      { keyword: `${word} price in ${cleanArea}`, intent: "price" },
      { keyword: `${word} supplier in ${cleanArea}`, intent: "supplier" },
      { keyword: `${word} dealer in ${cleanArea}`, intent: "dealer" },
      { keyword: `best ${word} in ${cleanArea}`, intent: "search" },
      { keyword: `post requirement for ${word} in ${cleanArea}`, intent: "rfq" },
    ];

    if (module === "materials") {
      items.push(
        { keyword: `${word} wholesale in ${cleanArea}`, intent: "wholesale" },
        { keyword: `${word} dokan in ${cleanArea}`, intent: "dealer" },
        { keyword: `${word} rate today in ${cleanArea}`, intent: "price" }
      );
    }

    if (module === "services") {
      items.push(
        { keyword: `${word} service in ${cleanArea}`, intent: "service" },
        { keyword: `${word} repair in ${cleanArea}`, intent: "repair" },
        { keyword: `${word} contact number in ${cleanArea}`, intent: "service" }
      );
    }

    if (module === "rentals") {
      items.push(
        { keyword: `${word} per day rent in ${cleanArea}`, intent: "rental" },
        { keyword: `${word} hourly rent in ${cleanArea}`, intent: "rental" },
        { keyword: `${word} booking in ${cleanArea}`, intent: "rental" }
      );
    }

    return items;
  });
}

export function getRegionalKeywordGroups(module: SeoModule, area: string) {
  const keywords = getRegionalKeywords(module, area);

  return {
    search: keywords.filter((item) => item.intent === "search"),
    nearMe: keywords.filter((item) => item.intent === "near_me"),
    price: keywords.filter((item) => item.intent === "price"),
    supplier: keywords.filter((item) => item.intent === "supplier"),
    dealer: keywords.filter((item) => item.intent === "dealer"),
    wholesale: keywords.filter((item) => item.intent === "wholesale"),
    rfq: keywords.filter((item) => item.intent === "rfq"),
    service: keywords.filter((item) => item.intent === "service"),
    repair: keywords.filter((item) => item.intent === "repair"),
    rental: keywords.filter((item) => item.intent === "rental"),
    installation: keywords.filter((item) => item.intent === "installation"),
  };
}