"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { Container } from "@/components/layout/Container";
import { SectionHeader } from "@/components/layout/SectionHeader";
import { Card, CardBody } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { EmptyState } from "@/components/ui/EmptyState";

type Status="available"|"hold"|"booked"|"sold"|"blocked";
type Unit={id:string;unit_code:string|null;title:string|null;unit_kind:string;tower:string|null;block:string|null;floor_no:number|null;unit_no:string|null;facing:string|null;status:Status;price:number|null;plot_area_sqft:number|null;built_up_sqft:number|null;carpet_sqft:number|null;super_built_up_sqft:number|null;dimension_length_ft:number|null;dimension_width_ft:number|null;boundary_north:string|null;boundary_south:string|null;boundary_east:string|null;boundary_west:string|null;land_vacancy_status:string|null;existing_structure_type:string|null;boundary_demarcation_type:string|null;trust_status:string;listingId:string|null};
type Data={project:{name:string;description:string|null;city:string|null;district:string|null;state:string|null};catalogs:Array<{id:string;name:string;kind:string}>;units:Unit[];ownerPreview:boolean};
const styles:Record<Status,{label:string;bg:string;border:string;color:string}>={available:{label:"Available",bg:"#ecfdf5",border:"#10b981",color:"#065f46"},hold:{label:"Temporarily Held",bg:"#fffbeb",border:"#f59e0b",color:"#92400e"},booked:{label:"Booked",bg:"#eff6ff",border:"#3b82f6",color:"#1e40af"},sold:{label:"Sold",bg:"#f3f4f6",border:"#6b7280",color:"#374151"},blocked:{label:"Unavailable",bg:"#fef2f2",border:"#ef4444",color:"#991b1b"}};
const money=(v:number|null)=>v==null?"Price pending":`₹${new Intl.NumberFormat("en-IN",{maximumFractionDigits:0}).format(v)}`;
const area=(u:Unit)=>{const v=u.plot_area_sqft??u.carpet_sqft??u.built_up_sqft??u.super_built_up_sqft;return v==null?"Area pending":`${v.toLocaleString("en-IN")} sq.ft.`};
const human=(value:string|null)=>value?value.split("_").map((word)=>word[0]?.toUpperCase()+word.slice(1)).join(" "):"Pending";

export default function ProjectBuyerSelectorPage(){
 const {slug}=useParams<{slug:string}>(); const search=useSearchParams(); const preview=search.get("preview")==="builder";
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[filter,setFilter]=useState<"all"|Status>("all"),[selectedId,setSelectedId]=useState<string|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setError("");fetch(`/api/property/projects/${encodeURIComponent(slug)}${preview?"?preview=builder":""}`,{credentials:"include",cache:"no-store",headers:{Accept:"application/json"}}).then(async r=>{const p=await r.json().catch(()=>null);if(!r.ok||p?.ok!==true)throw new Error(p?.error?.message||"Unable to load project.");if(active)setData(p.data)}).catch(e=>active&&setError(e instanceof Error?e.message:"Unable to load project.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[slug,preview]);
 const units=useMemo(()=>(data?.units??[]).filter(u=>filter==="all"||u.status===filter),[data,filter]); const selected=data?.units.find(u=>u.id===selectedId)??null;
 if(loading)return <Container><EmptyState message="Loading project inventory…"/></Container>; if(error||!data)return <Container><EmptyState message={error||"Project not found."}/></Container>;
 return <Container>
  <SectionHeader title={data.project.name} subtitle="Select and compare a specific property unit—just like choosing a seat."/>
  {data.ownerPreview?<div style={{marginBottom:14,padding:12,border:"1px solid #93c5fd",borderRadius:12,background:"#eff6ff",fontWeight:800}}>Builder Preview: pending and unverified units are visible only to you. General buyers see verified units only.</div>:null}
  <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:14}}><Link href="/property/projects">← Projects</Link>{(["all","available","hold","booked","sold","blocked"] as const).map(v=><button key={v} type="button" onClick={()=>setFilter(v)} style={{padding:"8px 12px",borderRadius:999,border:filter===v?"2px solid #111827":"1px solid #d1d5db",background:"white",fontWeight:800}}>{v==="all"?"All":styles[v].label}</button>)}</div>
  <Card><CardBody><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}><Badge>Units: {data.units.length}</Badge><Badge>Showing: {units.length}</Badge>{data.project.city?<Badge>{[data.project.city,data.project.district,data.project.state].filter(Boolean).join(", ")}</Badge>:null}</div>
   {units.length===0?<EmptyState message={data.ownerPreview?"No units match this filter.":"No verified units are available to buyers yet."}/>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(130px,1fr))",gap:12}}>{units.map(u=>{const s=styles[u.status]??styles.blocked;return <button key={u.id} type="button" onClick={()=>setSelectedId(u.id)} aria-pressed={selectedId===u.id} style={{minHeight:116,padding:12,borderRadius:16,border:selectedId===u.id?"3px solid #111827":`2px solid ${s.border}`,background:s.bg,color:s.color,textAlign:"left",cursor:"pointer",opacity:u.status==="available"?1:.78}}><strong style={{display:"block",fontSize:16}}>{u.unit_code||u.unit_no||"Unit"}</strong><span style={{display:"block",marginTop:6,fontSize:12}}>{s.label}</span><span style={{display:"block",marginTop:6,fontSize:12,fontWeight:800}}>{money(u.price)}</span></button>})}</div>}
  </CardBody></Card>
  {selected?<><div style={{height:16}}/><Card><CardBody><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div style={{fontSize:12,fontWeight:900,color:"#2563eb"}}>SELECTED UNIT</div><h2 style={{margin:"5px 0"}}>{selected.title||selected.unit_code||"Property unit"}</h2></div><Badge>{styles[selected.status]?.label||"Unavailable"}</Badge></div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:14}}>{[["Type",selected.unit_kind],["Price",money(selected.price)],["Area",area(selected)],["Floor",selected.floor_no??"—"],["Facing",selected.facing||"—"],["Tower / Block",[selected.tower,selected.block].filter(Boolean).join(" / ")||"—"],["Dimensions",selected.dimension_length_ft&&selected.dimension_width_ft?`${selected.dimension_length_ft} × ${selected.dimension_width_ft} ft`:"—"],["Trust",selected.trust_status]].map(([l,v])=><div key={String(l)} style={{padding:12,background:"#f8fafc",borderRadius:12}}><small>{l}</small><strong style={{display:"block",marginTop:4}}>{v}</strong></div>)}</div>
   {selected.unit_kind==="plot"?<div style={{marginTop:14,padding:14,borderRadius:12,background:"#eff6ff"}}><strong>Present land condition</strong><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8,marginTop:8}}><div><b>Vacancy:</b> {human(selected.land_vacancy_status)}</div><div><b>Existing structure:</b> {human(selected.existing_structure_type)}</div><div><b>Boundary marking:</b> {human(selected.boundary_demarcation_type)}</div></div></div>:null}
   <div style={{marginTop:14,padding:14,borderRadius:12,background:"#f8fafc"}}><strong>Legal four-side boundaries</strong><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8,marginTop:8}}>{[["North",selected.boundary_north],["South",selected.boundary_south],["East",selected.boundary_east],["West",selected.boundary_west]].map(([side,v])=><div key={side}><b>{side}:</b> {v||"Pending"}</div>)}</div></div>
   <div style={{marginTop:16}}>{selected.listingId?<Link href={`/property/${selected.listingId}`} style={{fontWeight:900}}>View full property details →</Link>:<span style={{color:"#64748b"}}>Full listing and booking actions will appear after verification and publication.</span>}</div>
  </CardBody></Card></>:null}
 </Container>
}
