"use client";
import Link from "next/link";import {useEffect,useMemo,useRef,useState} from "react";import {useParams} from "next/navigation";
import {Container} from "@/components/layout/Container";import {SectionHeader} from "@/components/layout/SectionHeader";import {Card,CardBody} from "@/components/ui/Card";import {ActionButton} from "@/components/ui/ActionButton";import {Badge} from "@/components/ui/Badge";
type Unit={id:string;unit_code:string|null;title:string|null;status:string;unit_kind:string};type Placement={layout_id?:string;unit_id:string;position_x:number;position_y:number;width:number;height:number;rotation:number;label_override:string|null};type Layout={id:string;version:number;name:string;status:string;canvas_width:number;canvas_height:number;placements:Placement[]};
const num=(v:unknown)=>Number(v);const palette:Record<string,string>={available:"#10b981",hold:"#f59e0b",booked:"#3b82f6",sold:"#6b7280",blocked:"#ef4444"};
export default function ProjectLayoutEditor(){const {projectId}=useParams<{projectId:string}>();const [units,setUnits]=useState<Unit[]>([]),[layouts,setLayouts]=useState<Layout[]>([]),[layoutId,setLayoutId]=useState(""),[name,setName]=useState("Main project layout"),[placements,setPlacements]=useState<Placement[]>([]),[message,setMessage]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);const canvas=useRef<HTMLDivElement>(null);
 const layout=layouts.find(x=>x.id===layoutId);const placedIds=useMemo(()=>new Set(placements.map(x=>x.unit_id)),[placements]);
 async function load(preferred?:string){const r=await fetch(`/api/property/builder/projects/${projectId}/layout`,{cache:"no-store"}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Could not load layouts.");setUnits(j.data.units);setLayouts(j.data.layouts);const chosen=j.data.layouts.find((x:Layout)=>x.id===(preferred||layoutId))??j.data.layouts.find((x:Layout)=>x.status==="draft")??j.data.layouts[0];if(chosen){setLayoutId(chosen.id);setName(chosen.name);setPlacements(chosen.placements);}else{setLayoutId("");setPlacements([]);}}
 useEffect(()=>{load().catch(e=>setError(e.message))},[projectId]);
 function choose(id:string){const x=layouts.find(v=>v.id===id);setLayoutId(id);if(x){setName(x.name);setPlacements(x.placements)}else{setName("Main project layout");setPlacements([])}}
 function add(unit:Unit){const i=placements.length;setPlacements(v=>[...v,{unit_id:unit.id,position_x:5+(i%6)*15,position_y:5+Math.floor(i/6)*14,width:12,height:10,rotation:0,label_override:null}])}
 function drag(e:React.DragEvent,unitId:string){if(!canvas.current)return;const r=canvas.current.getBoundingClientRect();const x=Math.max(0,Math.min(88,(e.clientX-r.left)/r.width*100-6)),y=Math.max(0,Math.min(90,(e.clientY-r.top)/r.height*100-5));setPlacements(v=>v.map(p=>p.unit_id===unitId?{...p,position_x:x,position_y:y}:p))}
 async function save(){setSaving(true);setError("");try{const body={layoutId:layout?.status==="draft"?layoutId:null,name,canvasWidth:1200,canvasHeight:800,placements:placements.map(p=>({unitId:p.unit_id,x:num(p.position_x),y:num(p.position_y),width:num(p.width),height:num(p.height),rotation:num(p.rotation),label:p.label_override}))};const r=await fetch(`/api/property/builder/projects/${projectId}/layout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Save failed.");await load(j.data.layoutId);setMessage(`Draft version ${j.data.version} saved.`)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function publish(){if(!layoutId)return;setSaving(true);setError("");try{const r=await fetch(`/api/property/builder/projects/${projectId}/layout`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({layoutId})}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.error?.message||"Publish failed.");await load(layoutId);setMessage(`Version ${j.data.version} published for buyers.`)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 return <Container><SectionHeader title="Project Layout Editor" subtitle="Position exact units on a versioned buyer-facing map." right={<Link href={`/property/builder/projects/${projectId}/units`}><ActionButton variant="secondary">Back to Units</ActionButton></Link>}/>{error?<p style={{color:"#991b1b"}}>{error}</p>:null}{message?<p style={{color:"#065f46"}}>{message}</p>:null}<Card><CardBody><div style={{display:"flex",gap:10,flexWrap:"wrap",alignItems:"end"}}><label>Version<br/><select value={layoutId} onChange={e=>choose(e.target.value)}><option value="">New draft</option>{layouts.map(x=><option key={x.id} value={x.id}>v{x.version} · {x.status}</option>)}</select></label><label>Layout name<br/><input value={name} onChange={e=>setName(e.target.value)}/></label><ActionButton onClick={save} disabled={saving}>{saving?"Saving…":"Save Draft"}</ActionButton><ActionButton onClick={publish} disabled={saving||!layoutId||layout?.status!=="draft"}>Publish</ActionButton>{layout?<Badge>v{layout.version} · {layout.status}</Badge>:null}</div></CardBody></Card><div style={{height:12}}/><Card><CardBody><b>Unplaced units</b><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}>{units.filter(u=>!placedIds.has(u.id)).map(u=><button key={u.id} onClick={()=>add(u)} style={{padding:8,border:"1px solid #cbd5e1",borderRadius:9}}>+ {u.unit_code||u.title}</button>)}</div><p style={{fontSize:13,color:"#64748b"}}>Add a unit, then drag its tile to the correct position. Status colours always come from live inventory.</p><div ref={canvas} onDragOver={e=>e.preventDefault()} style={{position:"relative",width:"100%",aspectRatio:"3 / 2",minHeight:420,border:"2px dashed #94a3b8",borderRadius:14,backgroundImage:"linear-gradient(#e2e8f0 1px,transparent 1px),linear-gradient(90deg,#e2e8f0 1px,transparent 1px)",backgroundSize:"5% 5%"}}>{placements.map(p=>{const u=units.find(x=>x.id===p.unit_id);return <button key={p.unit_id} draggable onDragEnd={e=>drag(e,p.unit_id)} title="Drag to position" style={{position:"absolute",left:`${p.position_x}%`,top:`${p.position_y}%`,width:`${p.width}%`,height:`${p.height}%`,minWidth:55,minHeight:42,border:`2px solid ${palette[u?.status||"blocked"]}`,borderRadius:9,background:"white",fontWeight:800,cursor:"grab",transform:`rotate(${p.rotation}deg)`}}>{p.label_override||u?.unit_code||"Unit"}<small style={{display:"block"}}>{u?.status}</small></button>})}</div></CardBody></Card></Container>}
