export const LGD_STATES = [
  { slug: "andaman-and-nicobar-islands", name: "Andaman and Nicobar Islands", lgdCode: 35 },
  { slug: "andhra-pradesh", name: "Andhra Pradesh", lgdCode: 28 },
  { slug: "arunachal-pradesh", name: "Arunachal Pradesh", lgdCode: 12 },
  { slug: "assam", name: "Assam", lgdCode: 18 },
  { slug: "bihar", name: "Bihar", lgdCode: 10 },
  { slug: "chandigarh", name: "Chandigarh", lgdCode: 4 },
  { slug: "chhattisgarh", name: "Chhattisgarh", lgdCode: 22 },
  { slug: "dadra-and-nagar-haveli-and-daman-and-diu", name: "Dadra and Nagar Haveli and Daman and Diu", lgdCode: 38 },
  { slug: "delhi", name: "Delhi", lgdCode: 7 },
  { slug: "goa", name: "Goa", lgdCode: 30 },
  { slug: "gujarat", name: "Gujarat", lgdCode: 24 },
  { slug: "haryana", name: "Haryana", lgdCode: 6 },
  { slug: "himachal-pradesh", name: "Himachal Pradesh", lgdCode: 2 },
  { slug: "jammu-and-kashmir", name: "Jammu and Kashmir", lgdCode: 1 },
  { slug: "jharkhand", name: "Jharkhand", lgdCode: 20 },
  { slug: "karnataka", name: "Karnataka", lgdCode: 29 },
  { slug: "kerala", name: "Kerala", lgdCode: 32 },
  { slug: "ladakh", name: "Ladakh", lgdCode: 37 },
  { slug: "lakshadweep", name: "Lakshadweep", lgdCode: 31 },
  { slug: "madhya-pradesh", name: "Madhya Pradesh", lgdCode: 23 },
  { slug: "maharashtra", name: "Maharashtra", lgdCode: 27 },
  { slug: "manipur", name: "Manipur", lgdCode: 14 },
  { slug: "meghalaya", name: "Meghalaya", lgdCode: 17 },
  { slug: "mizoram", name: "Mizoram", lgdCode: 15 },
  { slug: "nagaland", name: "Nagaland", lgdCode: 13 },
  { slug: "odisha", name: "Odisha", lgdCode: 21 },
  { slug: "puducherry", name: "Puducherry", lgdCode: 34 },
  { slug: "punjab", name: "Punjab", lgdCode: 3 },
  { slug: "rajasthan", name: "Rajasthan", lgdCode: 8 },
  { slug: "sikkim", name: "Sikkim", lgdCode: 11 },
  { slug: "tamil-nadu", name: "Tamil Nadu", lgdCode: 33 },
  { slug: "telangana", name: "Telangana", lgdCode: 36 },
  { slug: "tripura", name: "Tripura", lgdCode: 16 },
  { slug: "uttar-pradesh", name: "Uttar Pradesh", lgdCode: 9 },
  { slug: "uttarakhand", name: "Uttarakhand", lgdCode: 5 },
  { slug: "west-bengal", name: "West Bengal", lgdCode: 19 },
];

export function getLgdState(slug) {
  return LGD_STATES.find((state) => state.slug === slug);
}
